version: '3.3'

services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    restart: always

  ntp:
    image: cturra/ntp
    ports:
      - '123:123/udp'
    environment:
      - TZ=America/Sao_Paulo
    restart: always