version: '3.3'

services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    restart: always

  ntp:
    image: cturra/ntp
    ports:
      - '123:123/udp'
    environment:
      - TZ=America/Sao_Paulo
    restart: always
  
  samba:
    image: dperson/samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /~/samba/share:/mount
    environment:
      - SMB_USER=smbDocker
      - SMB_PASSWORD=1234
      - SMB_SHARE_NAME=share
    restart: always