version: '3.3'

networks:
  lan_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    restart: always
    networks:
      lan_network:
        ipv4_address: 172.18.0.2

  ntp:
    container_name: ntp
    image: cturra/ntp
    ports:
      - '123:123/udp'
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    networks:
      lan_network:
        ipv4_address: 172.18.0.3
  
  samba:
    container_name: samba
    image: dperson/samba
    ports:
      - '137:137/udp'
      - '138:138/udp'
      - '139:139'
      - '445:445'
    volumes:
      - ./samba:/mount
    environment:
      - USERID=1000
      - GROUPID=1000
    command: -s 'Public;/mount;yes;no;yes;all;none;none'
    restart: always
    networks:
      lan_network:
        ipv4_address: 172.18.0.4
  
  ssh:
    container_name: ssh
    image: rastasheep/ubuntu-sshd:18.04
    ports:
      - '3022:22'
    volumes:
      - ./ssh/id_rsa.pub:/root/.ssh/authorized_keys
    command: /usr/sbin/sshd -D