version: '3.3'

networks:
  intranet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    restart: always
    networks:
      intranet:
        ipv4_address: 172.18.0.2

  ntp:
    container_name: ntp
    image: cturra/ntp
    ports:
      - '123:123/udp'
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    networks:
      intranet:
        ipv4_address: 172.18.0.3
  
  samba:
    container_name: samba
    image: dperson/samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /~/samba/share:/mount
    environment:
      - SMB_USER=smbDocker
      - SMB_PASSWORD=1234
      - SMB_SHARE_NAME=share
    restart: always
    networks:
      intranet:
        ipv4_address: 172.18.0.4